### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by edherm** [dupchurch93/GoodCooks#3]
Hello GoodCooks Team!

Please review my feedback on your schema from below, discuss with your team, and let me know any questions or concerns that you may have.

## `Recipes` Table
- [x] `ingredients` and `instructions` columns
    - [x] You currently have these stored as text, but they both seem like they would benefit from being a list of individual items (possibly their own tables??). Check out the RecipeBox project from Week 10 - Wednesday for inspiration (hint: just before the "Getting Started" header).
## `Ratings` Table
- [x] Have you decided which of these columns (if any) will be optional? For instance, does a user have to give a recipe a `starRating` if they want to leave some comment/`content`? Do they have to leave a `content`/comment to leave a `starRating`? How will you prevent an empty (no `content`, no `starRating`) if you decide both should be nullable?

**Comment by dupchurch93** [comment]
Thanks for the feedback Ed. 
1. For the recipes table we decided to go with a simpler implementation first and just keep the ingredients and instructions pretty open ended. 
2. In the ratings schema we actually have that the content can be nullable, however the star ratings cannot. So someone can leave a star rating with no review, but cannot leave a review with no star rating.

**Comment by TranJohnny** [comment]
To add onto point 1, with Mitchell's advice, we are modeling our Recipes table off of the design of GoodReads, in that our database will be pre-seeded with recipes as opposed to having user submitted recipes.  As a stretch goal, we could implement a separate table for Ingredients, MeasurementUnits, and Specifications so that users can submit uniform recipes.

**Comment by edherm** [comment]
Hello Team!

Thanks for your responses here. Regarding #2 awesome! That's good to know.

For #1, it sounds like you've thought this through! 

I'll close this issue.

Ed
